services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=carros
    ports:
      - 5432:5432
    networks:
      - carros

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8090:80
    networks:
      - carros
networks:
  carros:
    driver: bridge