server:
  port: 8080
  servlet:
    context-path: /carros
spring:
  application:
    name: api-carros
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carros
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true